import type { Metadata, Viewport } from "next";
import { fontVariables } from "@/design/fonts";
import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Pia — l'agent de charge mentale parentale",
  description:
    "Dicte ce qui te passe par la tête, Pia s'occupe du reste : RDV, biberons, courses, vigilance, mémoire long-terme. Pour deux co-parents.",
  applicationName: "Pia",
  appleWebApp: {
    capable: true,
    title: "Pia",
    statusBarStyle: "default",
    startupImage: [
      // Placeholders — generated by `pnpm dlx pwa-asset-generator` in Phase 0 wrap-up.
      "/splash/apple-splash-1290-2796.png",
      "/splash/apple-splash-1179-2556.png",
      "/splash/apple-splash-1170-2532.png",
    ],
  },
  formatDetection: {
    telephone: false,
  },
  manifest: "/manifest.webmanifest",
  icons: {
    icon: [
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [
      { url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f5f2ea" },
    { media: "(prefers-color-scheme: dark)", color: "#15140f" },
  ],
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fr" data-theme="cream" className={fontVariables} suppressHydrationWarning>
      <body className="min-h-dvh bg-bg text-ink antialiased">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
